### ISSUE TITLE
Добавить группировку территорий по никнейму владельца

### ISSUE THREAD

**Issue by Red-Teapot** [Red-Teapot/bbyaworld.com#14]
Никнейм владельца получать из поля `name` территории, которое должно быть записано в определенном формате.

Формат поля:

```
<nickname>_<region_num>
```

Где:
- `nickname` - никнейм владельца территории
- `region_num` - номер территории (у одного владельца может быть несколько территорий)

Территории вида `social_#` - общественные территории.

(Да, остается баг, если зайдет игрок с ником `social`)

**Доделать**: сортировка списка территорий игрока таким же образом, как и сортировка общего списка. Например, если общий список отсортирован по убыванию площади, то и территории одного игрока сортировать по убыванию площади.

**Comment by Red-Teapot** [comment]
**Еще**: обрабатывать территории, поле `name` которых сохранено в неверном формате, отдельно: отображать в конце списка, например.

**Comment by VELLEVET** [comment]
Ещё просьба: сделать сортировку по-умолчанию так, чтобы сверху были самые крупные землевладельцы.

**Comment by VELLEVET** [comment]
Всё клёво!
Но договорились, что сортировку территорий игрока сделаем такую же, как и сортировка общего списка.
