### ISSUE TITLE
Сделать автоматический бэкап БД

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#18]
Это можно реализовать в рамках shared-хостинга?

Бэкапить только БД: форума и статистики онлайна (вроде, остальные не нужно).

Складывать на этот же хостинг, в отдельную папку.
Желательно ограничить количество бэкапов (например, до 10) и автоматом чистить лишние.

Регулярность - раз в сутки. Норм?

**Comment by Red-Teapot** [comment]
Кажется, есть автоматический бекап на shared-хостинге из коробки: ПУ - Автоматические резервные копии (В разделе "Базы данных и бекапы") - Архивы БД MySQL.

**Comment by VELLEVET** [comment]
Получается, что нам вообще не надо думать об этом?
http://imgur.com/a/2Xh4l

А почему бэкапы стали делаться ежедневно с 30-го августа?
Где это настраивается?

В любом случае, можно закрывать задачу.

**Comment by Red-Teapot** [comment]
> А почему бэкапы стали делаться ежедневно с 30-го августа?

Я не знаю

**Comment by VELLEVET** [comment]
Узнал инфу в ТП:

> Согласно п.3 договора сроки хранения таких резервных копий следующие:
> Бэкапы файлов содержат данные за последние три дня;
> Архивы БД включают ежедневные (за последнюю неделю) и еженедельные резервные копии.

Так что, за нас уже сделали все необходимые бэкапы для срочных откатов )
