### ISSUE TITLE
Перенести на VPS

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#20]
По сути, это просто вопрос с вариантами для обсуждения и возможностью отклонения по разным причинам.

Может, всё-таки рискнём и попробуем переехать на VPS к каталогу?
Причём, сначала просто попробуем перенести сайт и форум со всеми статистиками. А БД-плагина-логгера не будем переносить.

Посмотрим нагрузку на VPS.
Далее - увидим либо относительно приемлемую нагрузку, либо поймём, что нужно поднять тариф до U2 и можно перенести БД плагина-логгера, либо поймём, что это ад и надо быстро вернуться назад )))))

**Comment by Red-Teapot** [comment]
Я пока немного отрицательно отношусь к сваливанию всего на один VPS: боюсь, как бы какие-нибудь проблемы безопасности не повлияли на другой сайт.

И тут я думаю: использовать таки Docker (но это отдельная тема, которую еще распахивать надо), либо просто постараться хорошо все настроить.

У меня уже сейчас есть мысль по перенастройке сервера: поставить nginx для статики и тот же apache для динамики - должно дать прибавку к скорости работы.

**Comment by VELLEVET** [comment]
Вероятно, это будет сделано в рамках этих работ:  
https://forum.bbyaworld.com/index.php?/topic/753-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%84%D0%BE%D1%80%D1%83%D0%BC%D0%B0/  

----------
  
Вообще, ещё грешу на хостинг, который стал хуже работать в последние месяцы:  
http://imgur.com/a/O9YA6  
  
----------  
  
 = видимо, будем переезжать на OVH

**Comment by Red-Teapot** [comment]
Сделано.
