### ISSUE TITLE
Разное количество игроков на сайте и на форуме

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#22]
Хз, как отловить этот баг, но у меня сейчас на сайте и на форуме показывается разное количество игроков. Не успел посчитать соответствие цифры и ников - через минуту на сайте уменьшилось количество игроков до количества, указанного на форуме.

**Comment by Red-Teapot** [comment]
Мне кажется, что это из-за кеша: на сайте список игроков кешируется на пять минут. Следовательно, он может запаздывать. А на форуме, видимо, никакого кеширования нет.

**Comment by Red-Teapot** [comment]
Могу грохнуть кеширование и на сайте, если надо.

**Comment by VELLEVET** [comment]
Не. Возможно, это не проблема. Просто попробовал обсудить. Видимо, можно закрывать )
