### ISSUE TITLE
Add staff list and free vacancies page

### ISSUE THREAD

**Issue by Red-Teapot** [Red-Teapot/bbyaworld.com#3]
Add page containing all server staff and free vacancies list (like [here](http://forum.bbyaworld.com/index.php?/topic/315-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%B8-%D0%B3%D0%B5%D0%B9%D0%BC%D0%BC%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B0/)).

Add link to this page in navbar 'Information' submenu.

**Comment by VELLEVET** [comment]
Может, давай оставим только ссылку из главного меню?

**Comment by Red-Teapot** [comment]
А куда ее добавить?

**Comment by VELLEVET** [comment]
Как и все остальные дополнительные ссылки - в меню "Информация" с текстом ссылки = "Вакансии"

**Comment by Red-Teapot** [comment]
Я так и собирался делать
