### ISSUE TITLE
Обновить инфу и данные

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#36]
Чайник, привет!
Можно попросить тебя пофиксить сайт?

Новый ip (213.32.8.157) для карты и статуса сервера + игроков онлайн (кстати, для удобства ip можно заменить на play.bbyaworld.com:25565 - а я через регистратора буду привязку к ip делать).

 + версия 1.11.2

**Comment by Red-Teapot** [comment]
> Новый ip (213.32.8.157) для карты и статуса сервера + игроков онлайн (кстати, для удобства ip можно заменить на play.bbyaworld.com:25565 - а я через регистратора буду привязку к ip делать).

Кажется, так было сделано с самого начала.

Остальное сделаю по мере возможности, времени и сил.
