### ISSUE TITLE
Подсчёт размера зоны влияния кланов

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#37]
Чайник, скажи пожалуйста - можно сделать автоматический подсчёт зон влияния кланов на основе данных с Dynmap - также, как подсчёт терр?  
В плагине соты записываются так:
- id:SW_0031-0007 label:"SW_0031-0007 (free)", set:Clans  
  
Если сота свободная, то пишется free. Если сота захвачена, то пишется название клана вместо free.  

**По сути, нужно:**

- [ ] добавить страницу с инфой о размерах зоны влияния кланов в раздел информация ("Рейтинг кланов"?)
- [ ] считать раз в сутки количество сот у каждого клана и обновлять страницу
- [ ] сортировать их в порядке... убывания(?) - когда сверху самые влиятельные кланы.  
- [ ] Если какой-то клан расформировывается или захватывается, то его соты обнуляются и делаются free = из списка его тоже надо убирать.
- [ ] если можно, то было бы здорово выделять цветом первые 5 самых влиятельных кланов + все те, которые по размеру зоны влияния равны пятому клану
- [ ] если можно, то было бы здорово писать оставшееся количество свободных сот

**Comment by Red-Teapot** [comment]
На всякий, цитирую сюда сообщение из Скайпа.

> По идее, там примерно также, как с террами игроков.
> Основная задача - считать размер зоны влияния и формировать список участников Совета кланов.
> 
> - нужно искать территории (“соты”) в set = Clans с label = “<название_клана>”
> - кланы могут добавляться со временем и исчезать
> - сейчас такие кланы: ClanLess, Order of Light, THI, Druzhina, FEB, Lava, Elsirion https://forum.bbyaworld.com/index.php?/topic/33-%D0%BA%D0%BB%D0%B0%D0%BD%D1%8B/
> 
> Хз - видимо, тупо раз в сутки пробегаться по всем территориям в set = Clans.
> 
> Далее - на основе инфы о количестве “сот” - нужно составить список текущего состава “Совета кланов”:
> https://forum.bbyaworld.com/index.php?/topic/573-%D1%81%D0%BE%D0%B2%D0%B5%D1%82-%D0%BA%D0%BB%D0%B0%D0%BD%D0%BE%D0%B2/
> 
> Топ 5 основателей кланов - становятся участниками Совета кланов.
> Если на 5-ом месте несколько кланов, то все основатели кланов с одинаковым количеством сот - тоже входят в состав Совета кланов.
> 
> Разбить список на две части и во второй части перечислить тех, кто не входит в Совет кланов.
> 
> Ммм…
> По сути, это будет просто автоматический подсчёт размера зоны влияния кланов:
> - надо писать название клана (берётся из label)
> - справа писать количество сот
> - нумеровать список
> - разбить на две части
> - при одинаковом количестве сот для тех, кто борется за пятое место - всех разместить в первой половине списка = основатели этих кланов могут входить в Совет кланов
> 
> Надеюсь, более менее понятно + надеюсь, что учёл все нюансы.
