### ISSUE TITLE
Убрать все ссылки на Dynmap из правил

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#40]

**Comment by Red-Teapot** [comment]
Может, вообще все ссылки удалить из правил? А то смотрю, там куча ссылок ведет на старый форум. Часть сокращены, и я хз, куда они ведут - открывать ~20 ссылок влом.

Еще можно хорошо подумать и заменить все ссылки на актуальные + выпилить лишние.

**Comment by VELLEVET** [comment]
Давай уберём вообще все ссылки. Они были только на форуме.
