### ISSUE TITLE
Скорректировать меню информация

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#41]
Убрать ссылки на "Админ-шоу" и "Состав и вакансии".

**Comment by Red-Teapot** [comment]
Страницу "Состав и вакансии" удалять полностью?

**Comment by VELLEVET** [comment]
Видимо, да, т.к. в текущем виде (без админки что ли) - всё это корректировать можешь только ты = дёргать тебя из-за каждой мелочи анриал. А я пока так и не осилил обновление сайта ))))

С другой стороны, можно пока просто убрать ссылку из меню.
