### ISSUE TITLE
Переделать рейтинг кланов на новый слой.

### ISSUE THREAD

**Issue by VELLEVET** [Red-Teapot/bbyaworld.com#45]
Сабж.
Название слоя, вероятно - Clans2
https://forum.bbyaworld.com/index.php?/topic/1600-%D1%81%D0%B5%D1%82%D0%BA%D0%B0-%D0%BA%D0%BB%D0%B0%D0%BD%D0%BE%D0%B2-%D0%BD%D0%B0-dynmap/&page=2&tab=comments#comment-68996

**Comment by Red-Teapot** [comment]
Сделано
