### ISSUE TITLE
Add server age counter

### ISSUE THREAD

**Issue by Red-Teapot** [Red-Teapot/bbyaworld.com#5]
Count server age from **05.05.2012 19:58:21 MSK**.

Count in-game time.

**Comment by VELLEVET** [comment]
Давай, всё-таки, внутриигровое считать - больше атмосферности :)

**Comment by Red-Teapot** [comment]
@VELLEVET, а куда лучше поместить счетчик? Я не вижу для него места

**Comment by VELLEVET** [comment]
Действительно, не очень просто. Возможно, для нового внешнего вида, над которым ты работаешь, будет иметь смысл продумать совершенно новый подход.

Сейчас есть такой варинат: можно попробовать это преподнести чуть ли не как основную фишку, добавить аутентичности и разместить прям по центру страницы достаточно большим размером что-нибудь вроде - "Возраст мира: 303 лет" или "На сервере 300 год, новая эра". Для мобильных это будет не совсем центр, а середина пространства - между лайками соц.сетей и текстом слайдера.

Ещё можно убрать эти лайки в соц.сети, т.к. мало кто лайкает )

Ну, или для десктопа - в правый угол главного меню, а для мобильного скрыть или убрать в выпадающее меню.

P.S. вообще, надо бы подсмотреть, как пишут даты во всяких эпичных вещах... Например, в фильмах указывают тупо циферки и пишут год. Может, нам тоже писать тупо - "На сервере 304 год"? Можно ещё всплывающей подсказкой дать уточнение, что это по внутриигровому время исчислению.

**Comment by VELLEVET** [comment]
И где этот счётчик в итоге - в одном из слайдов, где написано сейчас 311 лет? :)
